# Generated by Django 2.2.5 on 2021-12-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20211203_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name_plural': 'Room Type'},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='amenity',
            new_name='amenities',
        ),
    ]
